parameters:
#    my_play_band_musica.example.class: MyPlayBand\MusicaBundle\Example

services:
#    my_play_band_musica.example:
#        class: %my_play_band_musica.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
