MyPlayBandMusicaBundle:
    resource: "@MyPlayBandMusicaBundle/Resources/config/routing.yml"
    prefix:   /

MyPlayBandArtistaBundle:
    resource: "@MyPlayBandArtistaBundle/Resources/config/routing.yml"
    prefix:   /

MyPlayBandTestBundle:
    resource: "@MyPlayBandTestBundle/Resources/config/routing.yml"
    prefix:   /

MyPlayBandUsuarioBundle:
    resource: "@MyPlayBandUsuarioBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
