parameters:
#    my_play_band_test.example.class: MyPlayBand\TestBundle\Example

services:
#    my_play_band_test.example:
#        class: %my_play_band_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
